### ISSUE TITLE
Podwójne powiadomienie

### ISSUE THREAD

**Issue by SebaZ** [djfoxer/dp.notification#1]
Prawdopodobnie powiadomienie o konkursie blogowym jest specyficznym powiadomieniem, ponieważ program pokazuje je podwójnie.

https://drive.google.com/file/d/0B2EiufXhuWotb0c4Y0N3SmNBejQ/view?usp=sharing

**Comment by djfoxer** [comment]
Dziwne zachowanie, nie spotkałem się z takim. Będę monitorował u siebie sytuację. Chyba, że nadal masz te podwójną notyfikację, to czy mógłbyś przesłać JSONa z przeglądarki? Jeśli to nie problem :)

**Comment by SebaZ** [comment]
Ciekawostka, powiadomienie nowe (nieoznaczone jako przeczytane) jest wyświetlane podwójnie https://drive.google.com/open?id=0B2EiufXhuWotSTBuNU5aV1VLaDQ

`{  
    "current":{  
        "1891600:302457":{  
            "Type":"comment",
            "UserName":"djfoxer",
            "Title":"",
            "Avatar":"http://avatarsb.dpcdn.pl/imgc/Avatar/142792/g_s_150x150_-_-_142792xbanner2.png.166ba2750d634faf204b8a7ff4c72c39_1452433452.png",
            "TargetUrl":"http://dp.do/c1891971",
            "Status":1,
            "CustomText":"",
            "Data":1464889750833
        },
        "6:308408":{  
            "Type":"contest",
            "UserName":"",
            "Title":"Konkurs blogowy - maj",
            "Avatar":"",
            "TargetUrl":"http://www.dobreprogramy.pl/NagradzamyBlogerow",
            "Status":1,
            "CustomText":"Głosuj na najciekawsze wpisy",
            "Data":1465125379767
        },
        "1894332:312278":{  
            "Type":"comment",
            "UserName":"djfoxer",
            "Title":"",
            "Avatar":"http://avatarsb.dpcdn.pl/imgc/Avatar/142792/g_s_150x150_-_-_142792xbanner2.png.166ba2750d634faf204b8a7ff4c72c39_1452433452.png",
            "TargetUrl":"http://dp.do/c1894446",
            "Status":1,
            "CustomText":"",
            "Data":1465173137420
        },
        "1894611:320975":{  
            "Type":"comment",
            "UserName":"djfoxer",
            "Title":"",
            "Avatar":"http://avatarsb.dpcdn.pl/imgc/Avatar/142792/g_s_150x150_-_-_142792xbanner2.png.166ba2750d634faf204b8a7ff4c72c39_1452433452.png",
            "TargetUrl":"http://dp.do/c1895842",
            "Status":0,
            "CustomText":"",
            "Data":1465344416850
        }
    }
}`

**Comment by djfoxer** [comment]
Ok, znalazłem buga w dodawaniu nowych powiadomień :) Fix pójdzie z kolejną wersją. Dzięki :)
